@walletHost = http://localhost:8080
@paymentHost = http://localhost:8081

### Seed wallets in badwallet-api
POST {{walletHost}}/api/wallets/seed?numWallets=10&eventsPerWallet=100

### Create wallet in badwallet-api
POST {{walletHost}}/api/wallets
Content-Type: application/json

{
  "phoneNumber": "+221779998877",
  "email": "testclient@gmail.com",
  "initialBalance": 25000,
  "code": "WLT-TEST001",
  "currency": "XOF"
}

### List wallets in badwallet-api
GET {{walletHost}}/api/wallets?page=0&size=10
Content-Type: application/json

### Get wallet by phone number in badwallet-api
GET {{walletHost}}/api/wallets/+221770000003
Content-Type: application/json

### Get wallet balance by phone number in badwallet-api
GET {{walletHost}}/api/wallets/+221770000003/balance
Content-Type: application/json

### Deposit into wallet in badwallet-api
POST {{walletHost}}/api/wallets/1/deposit
Content-Type: application/json

{
  "amount": 50000.00,
  "paymentMethod": "CREDIT_CARD"
}
