server.port=8080

spring.application.name=badwallet-api

spring.datasource.url=jdbc:h2:mem:badwalletdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.error.include-message=always

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

payment.service.base-url=http://localhost:8081
